services:
  wordpress-container:
    build: .
    container_name: wp-container-unix-sockets
    restart: always
    ports:
      - 8082:80
    environment:
      WORDPRESS_DB_HOST: db-container
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db-container:
    image: mysql:8.0
    container_name: db-container-unix-sockets
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
